name: CI Partie 2

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Recuperer le depot
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Installer les dependances
        run: npm ci

      - name: Executer ESLint
        run: npm run lint

  test:
    name: Tests Jest
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Recuperer le depot
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Installer les dependances
        run: npm ci

      - name: Executer les tests
        run: npm test

  security-deps:
    name: Securite des dependances et secrets
    runs-on: ubuntu-latest

    steps:
      - name: Recuperer tout l'historique Git
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Installer les dependances
        run: npm ci

      - name: Auditer les dependances
        run: npm audit --audit-level=high

      - name: Rechercher les secrets avec Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-push:
    name: Build et publication Docker
    runs-on: ubuntu-latest
    needs: 
        - test
        - security-deps

    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    steps:
      - name: Recuperer le depot
        uses: actions/checkout@v4

      - name: Configurer Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Connexion a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construire et publier l'image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/clickfast-game:${{ github.sha }}