name: CI Partie 2

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Recuperer le depot
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Installer les dependances
        run: npm ci

      - name: Executer ESLint
        run: npm run lint

  test:
    name: Tests Jest
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Recuperer le depot
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Installer les dependances
        run: npm ci

      - name: Executer les tests
        run: npm test
        